name: Release - Deploy All

on:
  push:
    branches:
      - 'releases/*'
  pull_request:
    branches:
      - 'releases/*'


jobs:

  functons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Run Eslint
        run: |
          cd functions
          npm install
          npm run lint
      - name: Deploy functions
        run: |
          cd functions
          npm install
          export FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
          npm run deploy

  hosting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Run Eslint
        run: |
          cd hosting
          npm install
          npm run lint
      - name: Deploy hosting
        run: |
          cd hosting
          npm install
          echo "GATSBY_API_KEY=${{ secrets.GATSBY_API_KEY }}\n"                           >> .env
          echo "GATSBY_AUTH_DOMAIN=${{ secrets.FIREBASE_DOMAIN }}\n"                      > .env
          echo "GATSBY_DATABASE_URL=${{ secrets.GATSBY_DATABASE_URL }}\n"                 > .env
          echo "GATSBY_PROJECT_ID=${{ secrets.GATSBY_PROJECT_ID }}\n"                     > .env
          echo "GATSBY_STORAGE_BUCKET=${{ secrets.GATSBY_STORAGE_BUCKET }}\n"             > .env
          echo "GATSBY_MESSAGING_SENDER_ID=${{ secrets.GATSBY_MESSAGING_SENDER_ID }}\n"   > .env
          echo "GATSBY_VAPID_KEY=${{ secrets.GATSBY_VAPID_KEY }}\n"                       > .env
          echo "GATSBY_APPID=${{ secrets.GATSBY_APPID }}\n"                               > .env
          npm run build
          export FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
          npm run deploy

  database_storage_firestore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Deploy Firebase Database, Storage, Firestore config
        run: |
          npm install -g firebase-tools
          firebase deploy --only database,storage,firestore --token ${{ secrets.FIREBASE_TOKEN }}
